### ISSUE TITLE
Message required if BT is turned off

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#131]
Habe eben die neueste Version installiert (commit 2294ee1c318fffb6eff20c641c2db84a12944b06) und wenn ich versuche mich mit einem Roboter zu verbinden erhalte ich folgende Fehlermeldung:

![image](https://user-images.githubusercontent.com/1516800/69483583-6e961900-0e29-11ea-92fd-e33000d4c96d.png)

Logcat zeigt folgenden Fehler:

	11-23 19:43:39.043 24110 24160 I ReactNativeJS: BleService scanning...
	11-23 19:43:39.353 24110 24161 E unknown:ReactNative: Exception in native call
	11-23 19:43:39.353 24110 24161 E unknown:ReactNative: com.facebook.react.bridge.UnexpectedNativeTypeException: Value for message cannot be cast from ReadableNativeMap to String
	11-23 19:43:39.353 24110 24161 E unknown:ReactNative:   at com.facebook.react.bridge.ReadableNativeMap.checkInstance(ReadableNativeMap.java:141)
	11-23 19:43:39.353 24110 24161 E unknown:ReactNative:   at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:129)
	11-23 19:43:39.353 24110 24161 E unknown:ReactNative:   at com.facebook.react.bridge.ReadableNativeMap.getString(ReadableNativeMap.java:163)
	11-23 19:43:39.353 24110 24161 E unknown:ReactNative:   at com.facebook.react.modules.dialog.DialogModule.showAlert(DialogModule.java:201)
	11-23 19:43:39.353 24110 24161 E unknown:ReactNative:   at java.lang.reflect.Method.invoke(Native Method)
	11-23 19:43:39.353 24110 24161 E unknown:ReactNative:   at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	11-23 19:43:39.353 24110 24161 E unknown:ReactNative:   at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
	11-23 19:43:39.353 24110 24161 E unknown:ReactNative:   at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	11-23 19:43:39.353 24110 24161 E unknown:ReactNative:   at android.os.Handler.handleCallback(Handler.java:883)
	11-23 19:43:39.353 24110 24161 E unknown:ReactNative:   at android.os.Handler.dispatchMessage(Handler.java:100)
	11-23 19:43:39.353 24110 24161 E unknown:ReactNative:   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	11-23 19:43:39.353 24110 24161 E unknown:ReactNative:   at android.os.Looper.loop(Looper.java:214)
	11-23 19:43:39.353 24110 24161 E unknown:ReactNative:   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
	11-23 19:43:39.353 24110 24161 E unknown:ReactNative:   at java.lang.Thread.run(Thread.java:919)
	11-23 19:43:39.386 24110 24110 D ReactNative: CatalystInstanceImpl.destroy() start
	11-23 19:43:39.390 24110 24267 D ReactNative: CatalystInstanceImpl.destroy() end
	11-23 19:43:39.394 24110 24110 W unknown:ReactNative: Tried to enqueue runnable on already finished thread: 'js... dropping Runnable.
	11-23 19:43:39.395 24110 24110 W MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {eaeeafc} sending message to a Handler on a dead thread
	11-23 19:43:39.395 24110 24110 W MessageQueue: java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {eaeeafc} sending message to a Handler on a dead thread
	11-23 19:43:39.395 24110 24110 W MessageQueue:  at android.os.MessageQueue.enqueueMessage(MessageQueue.java:558)
	11-23 19:43:39.395 24110 24110 W MessageQueue:  at android.os.Handler.enqueueMessage(Handler.java:754)
	11-23 19:43:39.395 24110 24110 W MessageQueue:  at android.os.Handler.sendMessageAtTime(Handler.java:703)
	11-23 19:43:39.395 24110 24110 W MessageQueue:  at android.os.Handler.sendMessageDelayed(Handler.java:673)
	11-23 19:43:39.395 24110 24110 W MessageQueue:  at android.os.Handler.post(Handler.java:403)
	11-23 19:43:39.395 24110 24110 W MessageQueue:  at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:70)
	11-23 19:43:39.395 24110 24110 W MessageQueue:  at com.facebook.react.bridge.ReactContext.runOnJSQueueThread(ReactContext.java:321)
	11-23 19:43:39.395 24110 24110 W MessageQueue:  at com.facebook.react.uimanager.events.EventDispatcher$ScheduleDispatchFrameCallback.doFrame(EventDispatcher.java:302)
	11-23 19:43:39.395 24110 24110 W MessageQueue:  at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:172)
	11-23 19:43:39.395 24110 24110 W MessageQueue:  at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
	11-23 19:43:39.395 24110 24110 W MessageQueue:  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964)
	11-23 19:43:39.395 24110 24110 W MessageQueue:  at android.view.Choreographer.doCallbacks(Choreographer.java:790)
	11-23 19:43:39.395 24110 24110 W MessageQueue:  at android.view.Choreographer.doFrame(Choreographer.java:721)
	11-23 19:43:39.395 24110 24110 W MessageQueue:  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
	11-23 19:43:39.395 24110 24110 W MessageQueue:  at android.os.Handler.handleCallback(Handler.java:883)
	11-23 19:43:39.395 24110 24110 W MessageQueue:  at android.os.Handler.dispatchMessage(Handler.java:100)
	11-23 19:43:39.395 24110 24110 W MessageQueue:  at android.os.Looper.loop(Looper.java:214)
	11-23 19:43:39.395 24110 24110 W MessageQueue:  at android.app.ActivityThread.main(ActivityThread.java:7356)
	11-23 19:43:39.395 24110 24110 W MessageQueue:  at java.lang.reflect.Method.invoke(Native Method)
	11-23 19:43:39.395 24110 24110 W MessageQueue:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	11-23 19:43:39.395 24110 24110 W MessageQueue:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by dgruntz** [comment]
`react-native log-android` gibt folgenden Text aus:

	[19:50:05] I | ReactNativeJS ?? Location permission granted

	[19:50:05] I | ReactNativeJS ?? true

	[19:50:20] I | ReactNativeJS ?? BleService scanning...

	[19:50:20] D | ReactNative ?? CatalystInstanceImpl.destroy() start

	[19:50:20] D | ReactNative ?? CatalystInstanceImpl.destroy() end

**Comment by dgruntz** [comment]
Habe das Problem gefunden: bei mir war BT ausgeschaltet; in diesem Fall sollte ebenfalls eine Meldung kommen dass BT aktiviert werden muss. Folgender Fehler wird beim Aufruf vo nstartDeviceScan geworfen:

    [19:53:59] I | ReactNativeJS ?? [BleError: BluetoothLE is powered off]

d.h. die Meldung (`error.message`) ist `BluetoothLE is powered off`.
